### ISSUE TITLE
[Chore] Increase test coverage

### ISSUE THREAD

**Issue by olivierobert** [thanakij/serp-api#2]
## Issue

Automated tests do not cover the core business logic (CSV upload, scraping).

## Expected

While 100% test coverage is not required for this code challenge, all critical paths of the application should be unit-tested (and, ideally, UI-tested). So the following should be covered:
- CSV parsing
- Keyword creation
- Keyword scraping
- Keyword listing

**Comment by thanakij** [comment]
I would use [cypress](https://nextjs.org/docs/pages/building-your-application/optimizing/testing#running-your-cypress-tests) for this as it covers both end-to-end testing and component-level testing.

```
--- a/package.json
+++ b/package.json
@@ -6,6 +6,10 @@
     "dev": "next dev",
     "build": "prisma generate && next build",
     "start": "next start",
+    "e2e": "start-server-and-test dev http://localhost:3000 \"cypress open --e2e\"",
+    "e2e:headless": "start-server-and-test dev http://localhost:3000 \"cypress run --e2e\"",
+    "component": "cypress open --component",
+    "component:headless": "cypress run --component",
     "lint": "next lint"
   },
   "dependencies": {
```

I would like to point out that the headless version of the test would be ideal for CI. Next, it would benefit the team the most if this testing is run against each pull request so that not only the reviewer see the actual code change but he/she can see the test result along with the change!

```
name: Run tests

on:
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  test:
    name: E2E Test
    runs-on: ubuntu-latest
    environment: non-production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: echo "${{ secrets.ENV_FILE }}" > .env.local
      - run: npm install
      - run: npm install --save-dev start-server-and-test
      - run: npm run build
      - run: npm run e2e:headless
      - run: npm run component:headless
```
